project:
  type: website
  output-dir: docs

website:
  title: "Financial Performance and Risk of Publicly Traded Companies"

  navbar:
    left:
      - href: index.qmd
        text: Home

      - href: introduction.qmd
        text: Introduction

      - href: dataprep_eda.qmd
        text: DataPrep/EDA

      - href: clustering.qmd
        text: Clustering

      - href: arm.qmd
        text: ARM (Association Rule Mining)

      - href: naivebayes.qmd
        text: NB

      - href: dectrees.qmd
        text: DT

      - href: svms.qmd
        text: SVM

      - href: regression.qmd
        text: Regression

      - href: nn.qmd
        text: NN

      - href: conclusions.qmd
        text: Conclusions

format:
  html:
    theme: cosmo
    toc: true
    number-sections: false
    smooth-scroll: true
    code-fold: true
    code-tools: true